#!/usr/bin/env bash
# install-guardian.sh — install the ADR-555 sovereign-shield guardian MCP as a
# LOCAL device service (the sovereign-device end-state of the BYOK onboarding).
#
#   bash install-guardian.sh [--dir DIR] [--port PORT] [--systemd]
#
# What it does, verbatim:
#   1. clones github.com/Synaptics-Lab/synaptic-fx-terminal into --dir
#      (or `git pull` if it already exists there)
#   2. npm install  (deps vendored in-repo — no workspace links needed)
#   3. npm run build (one-time production Next.js build; a few minutes)
#   4. writes ./start-guardian.sh that runs `next start -p PORT` with the
#      per-device key paths below
#   5. LIVE self-check: boots the server, tools/list + a real preflight_and_sign
#      call — both must pass before the installer exits 0
#   6. with --systemd: installs a `systemd --user` unit (autostart, restart)
#
# Per-device custody (generated by the app itself on first use, 0600, and
# NEVER shipped or synced anywhere):
#   ~/.synaptic/adr555/enclave-attest.key     (device Ed25519 attest key)
#   ~/.synaptic/adr555/shield-keyring.json    (imported BYOK identities)
set -euo pipefail

DIR="$HOME/synaptic-fx-terminal"
PORT=3007
SYSTEMD=0
REPO="https://github.com/Synaptics-Lab/synaptic-fx-terminal"
KEY_DIR="$HOME/.synaptic/adr555"

while [ $# -gt 0 ]; do
  case "$1" in
    --dir) DIR="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --systemd) SYSTEMD=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

echo "==> node version"
node --version || { echo "node is required (>=20). https://nodejs.org"; exit 1; }

echo "==> source into $DIR"
if [ -d "$DIR/.git" ]; then
  git -C "$DIR" pull --ff-only
else
  git clone --depth 1 "$REPO" "$DIR"
fi

echo "==> npm install (all deps in-repo)"
cd "$DIR"
npm install --no-audit --no-fund

echo "==> production build (one-time, a few minutes)"
npm run build

echo "==> per-device custody paths: $KEY_DIR"
mkdir -p "$KEY_DIR"

cat > start-guardian.sh <<EOF
#!/usr/bin/env bash
# ADR-555 guardian MCP (Sovereign Shield BYOK) on 127.0.0.1:$PORT
export ADR555_ENCLAVE_KEY_PATH="$KEY_DIR/enclave-attest.key"
export ADR555_SHIELD_KEYRING_PATH="$KEY_DIR/shield-keyring.json"
export NODE_ENV=production
exec npx next start -p $PORT
EOF
chmod 700 start-guardian.sh

echo "==> live self-check on 127.0.0.1:$PORT"
"$DIR/start-guardian.sh" &
SRV=$!
UP=0
for i in $(seq 1 30); do
  if curl -fsS "http://127.0.0.1:$PORT/api/enclave/mcp" -H 'content-type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"tools/list"}' > /tmp/guardian-boot.json 2>/dev/null; then
    UP=1; break
  fi
  sleep 1
done
kill $SRV 2>/dev/null || true
wait $SRV 2>/dev/null || true
[ "$UP" = 1 ] || { echo "server never answered tools/list — install FAILED"; exit 1; }

python3 - <<'PY'
import json
d = json.load(open("/tmp/guardian-boot.json"))
names = [t["name"] for t in d["result"]["tools"]]
need = ["shield_import", "shield_status", "shield_sign_xrpl_payment", "preflight_and_sign"]
missing = [n for n in need if n not in names]
print(f"tools listed: {len(names)}; shield surface present: {not missing}" + (f"; MISSING: {missing}" if missing else ""))
assert not missing, missing
PY
PREFLIGHT_MS=$(curl -fsS "http://127.0.0.1:$PORT/api/enclave/mcp" -H 'content-type: application/json' \
  -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"preflight_and_sign","arguments":{"uetr":"333e4587-9b30-4e21-8e7e-3ddffbe7db33","amount":1000,"pair":"USD/KES","debtor":"self-test debtor","creditor":"self-test creditor"}}}' \
  | python3 -c 'import sys,json; d=json.loads(json.load(sys.stdin)["result"]["content"][0]["text"]); assert d.get("passed") is True, d; t=d.get("performance",{}).get("total_ms","?"); print(t)')
echo "preflight self-test: PASS (${PREFLIGHT_MS} ms)"

if [ "$SYSTEMD" = 1 ]; then
  UNIT_DIR="$HOME/.config/systemd/user"
  mkdir -p "$UNIT_DIR"
  cat > "$UNIT_DIR/synaptic-adr555-guardian.service" <<EOF
[Unit]
Description=SynapticChain ADR-555 Guardian MCP (Sovereign Shield)
After=network.target

[Service]
WorkingDirectory=$DIR
ExecStart=$DIR/start-guardian.sh
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
EOF
  systemctl --user daemon-reload
  systemctl --user enable --now synaptic-adr555-guardian.service
  for i in $(seq 1 20); do
    curl -fsS "http://127.0.0.1:$PORT/api/enclave/mcp" -H 'content-type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"tools/list"}' >/dev/null 2>&1 && break
    sleep 1
  done
  echo "==> systemd user unit installed and serving (synaptic-adr555-guardian)"
else
  echo "==> start it now:   $DIR/start-guardian.sh"
  echo "==> autostart mode: rerun with --systemd"
fi

echo ""
echo "INSTALLED. This device is now an ADR-555 guardian node."
echo "Onboard your keys: https://wallet.synapticchain.xyz/shield/generator.html"